# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        server_version: 5.6
        host:     "%env(MYSQL_HOST)%"
        port:     "%env(MYSQL_PORT)%"
        dbname:   "%env(MYSQL_DATABASE)%"
        user:     "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASSWORD)%"
        charset:  utf8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                is_bundle: false
                prefix: App\Entity
                alias: App
