version: '2'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
    php:
        build: application
        environment:
            DEBUG: "true"
            SERVICE_NAME: ${SERVICE_NAME}
            SERVICE_DOMAIN: ${SERVICE_DOMAIN}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
        volumes:
            - ./application:/var/www:Z
            - ./logs/${SERVICE_NAME}.${SERVICE_DOMAIN}:/var/www/var/logs
    nginx:
        image: garlic/nginx
        ports:
            - 80:80
        volumes:
            - ./application:/var/www:Z
            - ./logs/nginx/:/var/log/nginx