version: '2'
services:
    rabbit:
        image: rancher/dns-service
        external_links:
            - Brokers/rabbit:rabbit
    db:
        image: mysql
        volumes:
            - "/data/${SERVICE_NAME}.${SERVICE_DOMAIN}/${MYSQL_DATABASE}/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        labels:
            io.rancher.container.pull_image: always
            database: true

    php:
        image: $DOCKERHUB_NAME/$SERVICE_NAME.$SERVICE_DOMAIN:$TAG
        labels:
            io.rancher.container.pull_image: always
            io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            production: true
        environment:
            MYSQL_HOST: "${MYSQL_HOST}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            DEBUG: "${DEBUG}"
            ENV: "${ENV}"
            SERVICE_NAMESPACE: "${SERVICE_NAMESPACE}"

    nginx:
        image: smmhub/nginx
        labels:
            traefik.port: 80
            traefik.frontend.rule: "Host:${FDQN_BACKEND}"
            io.rancher.container.pull_image: always
            io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            production: true
        volumes:
            - "nginx_logs:/var/log/nginx/${SERVICE_NAME}.${SERVICE_DOMAIN}"

    redis:
        image: "redis:alpine"
        labels:
            production: true
        volumes:
            - "./redis/data:/bitnami/redis"
volumes:
    nginx_logs:
