version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
  php:
    scale: 1
    retain_ip: true
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true