app:
    resource: "Controller/"
    type:     annotation

graphql:
    resource: "@GraphQLBundle/Controller/"

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }